# golangci-lint configuration for Hermes API
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Critical linters - must pass
    - errcheck      # Check for unchecked errors
    - govet         # Go vet checks (reduced to avoid fieldalignment)
    - staticcheck   # Static analysis checks
    - unused        # Check for unused code
    - gosimple      # Suggest code simplifications
    - ineffassign   # Detect ineffectual assignments
    
    # Code quality linters
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - gosec         # Security-focused linter
    - unconvert     # Remove unnecessary type conversions
    - bodyclose     # Check for HTTP response body close
    - nilerr        # Find returning nil error
    - errname       # Check error naming conventions
    - errorlint     # Check error wrapping
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Check function complexity
    - misspell      # Check for misspelled English words
    
    # Style linters (informational)
    - gocritic      # Comprehensive Go linter
    - revive        # Fast, configurable, extensible Go linter
    - whitespace    # Check for unnecessary whitespace
    
  disable:
    - typecheck        # Disabled as it can conflict with editor tools
    - godot            # Too strict - not requiring periods on all comments
    - nestif           # Can be overly strict for tests
    - unparam          # Can be noisy
    - exportloopref    # Deprecated in Go 1.22+
    - nilnil           # Too restrictive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*os.File).Close
  
  govet:
    enable-all: true
    disable:
      - shadow        # Can be too strict
      - fieldalignment # Memory optimization is premature here
  
  revive:
    rules:
      - name: exported
        disabled: true  # Can be noisy for internal packages
      - name: package-comments
        disabled: true  # Not always necessary for internal packages
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (handled by errcheck)
      - G304  # File path provided as variable (needed for file operations)
  
  gocyclo:
    min-complexity: 15  # Warn on functions with complexity > 15
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - unnamedResult  # Can be useful for clarity
      - hugeParam      # Sometimes large structs must be passed
      - ifElseChain    # if-else is often clearer than switch
      - paramTypeCombine # Separate params can be clearer
      - octalLiteral   # Old style is fine
      - emptyStringTest # len() check is idiomatic Go
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  errorlint:
    errorf: true
    asserts: true
    comparison: false  # Too strict - == nil is common pattern

issues:
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
    
    # Exclude certain checks in migrations
    - path: migrations/
      linters:
        - gosec
        - errcheck
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

